### ISSUE TITLE
running sloth does not produces all expected light shaders

### ISSUE THREAD

**Issue by illwieckz** [UnvanquishedAssets/tex-ex_src.dpkdir#1]
running sloth does not produces light shaders like `textures/shared_ex/light2_orange_3000` and other color and intensity variations, it's working in `tex-trak5_src.dpkdir` so I don't know yet what's happening.

**Comment by illwieckz** [comment]
note: this missing texture is visible in game on ceiling lamp in _hangar28_'s alien base (`lamp4.map`).

**Comment by illwieckz** [comment]
@Viech perhaps you can help me on that part, why running sloth on this texture set does not produces the same `.shader` files we currently ship in `.pk3`?

**Comment by mjstahlberg** [comment]
@illwieckz The current behaviour (not generating color variants) is because the addition maps in this repository already have colors of their own. Sloth opens addition maps to see if they are greyscale or colored, and it will only generate color variants if they are greyscale. (You wouldn't want color variants for everything that glows, e.g. computer panels with lamps or an exit sign.)

As to why the shipped files have color variants, I changed them to greyscale:
```
    Changes

        - Glow maps have been desaturated and put into grayscale mode.
        - Completely white alpha channels were removed.
        - File formats may have been converted.
```

If I remember correctly I sent you a huge archive of my local build toolchain that has the modified sources. Otherwise I can send you the files you are missing.

**Comment by illwieckz** [comment]
Oh I see, I will look at this. Thanks.

**Comment by illwieckz** [comment]
Thank you @Viech for pointing out the problem. I diffed your repository against mine (rgba against rgba) and I found 3 different files in two texture sets:

```
tex-ex_src.dpkdir/textures/shared_ex_src/light1_a.png
tex-ex_src.dpkdir/textures/shared_ex_src/light2_a.png
```

These ones look like to be very good candidate for that desaturation modification, and they are glow maps, and the second one is precisely the one that was faulty. Now Sloth produces the `light2_orange_3000` shader as expected, and the shader is now correctly displayed in the _hangar28_ map.

```
tex-pk02_src.dpkdir/textures/shared_pk02_src/light02_d.png
```

The one I had was yellow, yours is blue.

Every other texture in `tex-` repositories is binary equivalent with yours when converted to a pure rgba stream.
